name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install  # If you have dependencies to install

      - name: Build and deploy
        run: |
          npm run build  # Replace with your build command
          npx gh-pages -d dist  # Replace 'dist' with your build output directory
